# name: hackathon_pet
# description: A new Flutter project.

# version: 1.0.0+1

# environment:
#   sdk: ">=3.0.0 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^2.0.2

# flutter:
#   uses-material-design: true
#   # assets:
#   #  - images/a_dot_burr.jpeg
#   #  - images/a_dot_ham.jpeg
#   # fonts:
#   #   - family: Schyler
#   #     fonts:
#   #       - asset: fonts/Schyler-Regular.ttf
#   #       - asset: fonts/Schyler-Italic.ttf
#   #         style: italic
#   #   - family: Trajan Pro
#   #     fonts:
#   #       - asset: fonts/TrajanPro.ttf
#   #       - asset: fonts/TrajanPro_Bold.ttf
#   #         weight: 700
# flutter pub get flutter_tindercard

name: hackathon_pet
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tindercard: ^0.1.4  # Ensure to check for the latest version on pub.dev

dependency_overrides:
  flutter_tindercard: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.0.6 
  build_test: ^2.0.3

flutter:
  uses-material-design: true

  